# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BXerUnWjZXFp9mgM6ZUhq49-KiK_Dcth
"""

# ================================
#        REQUIRED INSTALLS
# ================================
# !pip install -q xlrd openpyxl beautifulsoup4 lxml

import re
import numpy as np
import pandas as pd
from pathlib import Path
from typing import Optional, Dict, List, Tuple
from bs4 import BeautifulSoup

# ==========================================
#  PART 0: FILE NORMALISER (ALL -> .XLSX)
# ==========================================

_CONVERTED_DIR = Path("_converted")
_CONVERTED_DIR.mkdir(exist_ok=True)

def _is_html_disguised_xls(p: Path) -> bool:
    try:
        head = p.read_bytes()[:4096].lower()
        return (b"<html" in head) or (b"<table" in head) or (b"<!doctype html" in head)
    except Exception:
        return False

def _html_table_to_grid(html_bytes: bytes):
    """
    Parse FIRST <table> into a 2D grid of strings.
    Preserves all rows exactly (no header inference).
    Expands colspan so the grid shape stays consistent.
    """
    soup = BeautifulSoup(html_bytes, "lxml")
    table = soup.find("table")
    if table is None:
        raise ValueError("HTML-backed .xls detected, but no <table> found.")

    rows = table.find_all("tr")
    grid = []

    for tr in rows:
        row_cells = []
        tds = tr.find_all(["td", "th"])
        for cell in tds:
            text = cell.get_text(separator=" ", strip=True)
            colspan = int(cell.get("colspan", 1) or 1)

            row_cells.append(text)
            for _ in range(colspan - 1):
                row_cells.append("")
        grid.append(row_cells)

    max_cols = max((len(r) for r in grid), default=0)
    for r in grid:
        if len(r) < max_cols:
            r.extend([""] * (max_cols - len(r)))

    return grid

def normalize_to_xlsx(src_path: Path) -> Path:
    """
    NORMALISE EVERYTHING to a fresh .xlsx (CloudConvert/Excel Save-As feel):
    - .xls, .xlsx, .xlsm, .csv -> .xlsx
    - Preserves ALL rows (no header inference)
    - Reads as text (no numeric/date coercion)
    - .xlsm macros are dropped by design
    - Handles HTML-disguised .xls (very common exports)
    """
    src_path = Path(src_path)
    if not src_path.exists():
        raise FileNotFoundError(src_path)

    _CONVERTED_DIR.mkdir(parents=True, exist_ok=True)
    out_path = _CONVERTED_DIR / f"{src_path.stem}__to_xlsx_exact.xlsx"
    ext = src_path.suffix.lower()

    if ext == ".csv":
        df = pd.read_csv(src_path, dtype=str, header=None)
        df.to_excel(out_path, index=False, header=False)
        return out_path

    if ext == ".xls" and _is_html_disguised_xls(src_path):
        grid = _html_table_to_grid(src_path.read_bytes())
        df = pd.DataFrame(grid)
        df.to_excel(out_path, index=False, header=False)
        return out_path

    if ext in [".xls", ".xlsx", ".xlsm"]:
        xls = pd.ExcelFile(src_path)
        with pd.ExcelWriter(out_path, engine="openpyxl") as writer:
            for sheet in xls.sheet_names:
                df = xls.parse(sheet_name=sheet, dtype=str, header=None)
                df.to_excel(writer, sheet_name=str(sheet)[:31], index=False, header=False)
        return out_path

    raise ValueError(f"Unsupported file type for normalization: {ext}")

# ==========================================
#  PART 1: CONFIG & REGISTRY
# ==========================================

CANON_COLS = ["Cheque/ NEFT/ UTR No.", "Claim No"]

FALLBACK_TPA_MIS_MAPS = {
    "IHX (Original MIS)": {
        "Cheque/ NEFT/ UTR No.": "Cheque/ NEFT/ UTR No.",
        "Claim No": "Claim Number"
    },
    "CARE HEALTH INSURANCE LIMITED": {
        "Cheque/ NEFT/ UTR No.": "Instrument/NEFT No",
        "Claim No": "AL Number"
    },
    "HEALTH INDIA INSURANCE TPA SERVICES PRIVATE LTD.": {
        "Cheque/ NEFT/ UTR No.": "utrnumber",
        "Claim No": "CCN"
    },
    "HERITAGE HEALTH INSURANCE TPA PRIVATE LIMITED": {
        "Cheque/ NEFT/ UTR No.": "UTR_NO",
        "Claim No": "HHCCN"
    },
    "MEDSAVE HEALTHCARE TPA PVT LTD": {
        "Cheque/ NEFT/ UTR No.": "UTR/Chq No.",
        "Claim No": "FILENO"
    },
    "PARAMOUNT HEALTHCARE": {
        "Cheque/ NEFT/ UTR No.": "UTR_NO",
        "Claim No": "Claim Number"
    },
    "PARK MEDICLAIM INSURANCE TPA PRIVATE LIMITED": {
        "Cheque/ NEFT/ UTR No.": "Chq No",
        "Claim No": "Claim Number"
    },
    "SAFEWAY INSURANCE TPA PVT.LTD": {
        "Cheque/ NEFT/ UTR No.": "Chequeno",
        "Claim No": "ClaimNo"
    },
    "STAR HEALTH & ALLIED HEALTH INSURANCE CO.LTD.": {
        "Cheque/ NEFT/ UTR No.": "UTR",
        "Claim No": "Insurer Claim Number"
    },
    "ADITYA BIRLA": {
        "Cheque/ NEFT/ UTR No.": "UTR Number",
        "Claim No": "CLAIM NO."
    },
    "FHPL": {
        "Cheque/ NEFT/ UTR No.": "Cheque/NEFT No",
        "Claim No": "Claim Id"
    },
    "FUTURE GENERALI": {
        "Cheque/ NEFT/ UTR No.": "Cheque/Ref No. Insured",
        "Claim No": "Claim No."
    },
    "GOOD HEALTH": {
        "Cheque/ NEFT/ UTR No.": "TRASACTION_NO",
        "Claim No": "CCN_NO"
    },
    "VOLO HEALTH INSURANCE TPA PVT.LTD (EWA) (Mail Extract)": {
        "Cheque/ NEFT/ UTR No.": "UTR Number",
        "Claim No": "Alternate Claim Id"
    },

    # ---- NEW LOT (patched) ----
    "VIDAL": {
        "Cheque/ NEFT/ UTR No.": "Cheque Number",
        "Claim No": "Claim Number"
    },
    "SBI GENERAL": {
        "Cheque/ NEFT/ UTR No.": "Payment Transaction ID UTR",
        "Claim No": "Claim No"
    },
    "RELIANCE": {
        "Cheque/ NEFT/ UTR No.": "Map Cheque/Neft Number",
        "Claim No": "Claim Number"
    },
    "ICICI LOMBARD": {
        "Cheque/ NEFT/ UTR No.": "Claim-Cheque Number",
        "Claim No": "Claim Number"
    },
    "ERICSON": {
        "Cheque/ NEFT/ UTR No.": "UTRNo",
        "Claim No": "ClaimId"
    }
}

def get_tpa_mis_maps() -> Dict[str, Dict[str, str]]:
    try:
        from database import tpa_mappings_collection
        if tpa_mappings_collection is not None:
            cursor = tpa_mappings_collection.find()
            docs = list(cursor)
            if docs:
                return {
                    doc["tpa_name"]: {
                        "Cheque/ NEFT/ UTR No.": doc["cheque_utr_column"],
                        "Claim No": doc["claim_no_column"]
                    } for doc in docs
                }
    except Exception:
        pass
    return FALLBACK_TPA_MIS_MAPS

# ==========================================
#  GLOBAL HARDENING: KEY CLEANING (CRITICAL)
# ==========================================

_NULL_TOKENS = {"", "nan", "none", "null", "na", "n/a", "n\\a", "0", "0.0"}

def _clean_key_series(series: pd.Series) -> pd.Series:
    s = series.copy()
    s = s.astype("string")
    s = s.str.replace("\xa0", " ", regex=False).str.strip()
    lower = s.str.lower()
    s = s.mask(lower.isin(_NULL_TOKENS), pd.NA)
    return s.astype(object).where(s.notna(), np.nan)

def _clean_key_value(x) -> Optional[str]:
    if pd.isna(x):
        return None
    s = str(x).replace("\xa0", " ").strip()
    if s.lower() in _NULL_TOKENS:
        return None
    return s

def _norm_colname(x: str) -> str:
    if x is None:
        return ""
    s = str(x)
    s = s.replace("\xa0", " ")
    s = s.replace("\n", " ").replace("\r", " ")
    s = re.sub(r"\s+", " ", s).strip()
    s = s.replace("–", "-").replace("—", "-").replace("−", "-")
    return s.upper()

def _make_unique_columns(cols) -> list:
    seen = {}
    out = []
    for c in list(cols):
        base = str(c).replace("\xa0", " ").strip()
        if base == "" or base.lower() in ("nan", "none", "null"):
            base = "UNNAMED"
        if base not in seen:
            seen[base] = 0
            out.append(base)
        else:
            seen[base] += 1
            out.append(f"{base}__DUP{seen[base]}")
    return out

def _force_series(x):
    if isinstance(x, pd.DataFrame):
        return x.iloc[:, 0]
    return x

# ==========================================
#  AUDIT / REVIEW HELPERS
# ==========================================

_AUDIT_FRONT_COLS = [
    "AUTO_REVIEW_STATUS",
    "REVIEW_STAGE",
    "REVIEW_REASON",
    "PAIR_STATUS",
    "MATCH_CARDINALITY",
    "LEFT_MATCH_COUNT",
    "RIGHT_MATCH_COUNT",
    "BANK_TYPE",
    "TPA_CHOICE",
    "MATCH_MODE",
    "RUN_ID",
    "UTR_RAW",
    "CLAIM_RAW",
    "PAIR_KEY_RAW",
    "UTR_KEY",
    "CLAIM_KEY",
    "PAIR_KEY",
]

def _safe_str(x) -> str:
    if pd.isna(x):
        return ""
    return str(x).replace("\xa0", " ").strip()

def _pair_key_raw(utr_raw, claim_raw) -> str:
    return f"{_safe_str(utr_raw)}||{_safe_str(claim_raw)}"

def _pair_key_clean(utr_key, claim_key) -> str:
    return f"{_safe_str(utr_key)}||{_safe_str(claim_key)}"

def _ordered_with_audit_front(df: pd.DataFrame) -> pd.DataFrame:
    front = [c for c in _AUDIT_FRONT_COLS if c in df.columns]
    rest = [c for c in df.columns if c not in front]
    return df[front + rest].copy()

def _cardinality_label(left_n: int, right_n: int) -> str:
    if left_n == 1 and right_n == 1:
        return "ONE_TO_ONE"
    if left_n == 1 and right_n > 1:
        return "ONE_TO_MANY"
    if left_n > 1 and right_n == 1:
        return "MANY_TO_ONE"
    return "MANY_TO_MANY"

def _pair_status_from_counts(n: int) -> str:
    return "PAIR_UNIQUE" if int(n) == 1 else "PAIR_DUPLICATE"

def _build_review_reason(pair_status: str, cardinality: str) -> str:
    if cardinality == "ONE_TO_ONE":
        return f"{pair_status} | {cardinality}"
    return f"{pair_status} | {cardinality}"

def _ensure_required_columns(df: pd.DataFrame, required: List[str], label: str):
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"{label}: missing required column(s): {missing}")

def _sanitize_for_output(df: pd.DataFrame) -> pd.DataFrame:
    drop_cols = [c for c in df.columns if c.startswith("_")]
    if drop_cols:
        df = df.drop(columns=drop_cols, errors="ignore")
    return _ordered_with_audit_front(df)

# ==========================================
#  PART 2: CLEANERS (BANK)
# ==========================================

def clean_raw_bank_statement_icici(path):
    def _extract_table_from_raw(raw):
        if raw.dropna(how="all").empty:
            return None

        header_row_idx = None
        for i, row in raw.iterrows():
            vals = [str(v).strip() for v in row.tolist() if pd.notna(v)]
            if "Transaction ID" in vals and "Description" in vals:
                header_row_idx = i
                break

        if header_row_idx is None:
            if len(raw) > 6:
                header_row_idx = 6
            else:
                return None

        header_vals = [str(x).strip() for x in raw.iloc[header_row_idx].tolist()]
        df = raw.iloc[header_row_idx + 1:].copy()

        if df.shape[1] < len(header_vals):
            for _ in range(len(header_vals) - df.shape[1]):
                df[df.shape[1]] = np.nan

        df = df.iloc[:, :len(header_vals)]
        df.columns = header_vals
        return df

    path = Path(path)
    ext = path.suffix.lower()
    tables = []

    if ext in [".xlsx", ".xls", ".xlsm"]:
        xls = pd.ExcelFile(path)
        for sheet in xls.sheet_names:
            raw = xls.parse(sheet_name=sheet, header=None)
            tbl = _extract_table_from_raw(raw)
            if tbl is not None:
                tables.append(tbl)

    elif ext == ".csv":
        raw = pd.read_csv(path, header=None)
        tbl = _extract_table_from_raw(raw)
        if tbl is not None:
            tables.append(tbl)

    else:
        try:
            raw = pd.read_excel(path, header=None)
        except:
            raw = pd.read_csv(path, header=None)
        tbl = _extract_table_from_raw(raw)
        if tbl is not None:
            tables.append(tbl)

    if not tables:
        raise ValueError("ICICI bank parser: No usable transaction table found.")

    df_all = pd.concat(tables, ignore_index=True)

    keep_cols = [
        "No.",
        "Transaction ID",
        "Txn Posted Date",
        "Description",
        "Cr/Dr",
        "Transaction Amount(INR)",
    ]
    existing = [c for c in keep_cols if c in df_all.columns]
    df = df_all[existing].copy()

    df = df.loc[:, ~df.columns.duplicated()].copy()
    df = df.dropna(how="all")

    if not df.empty:
        def _is_repeated_header(row):
            for c in existing:
                if str(row[c]).strip() != c:
                    return False
            return True
        df = df[~df.apply(_is_repeated_header, axis=1)]

    if "Description" in df.columns:
        desc = df["Description"].astype(str).str.upper()
        pattern = (
            r"TOTAL|OPENING BALANCE|CLOSING BALANCE|"
            r"BALANCE BROUGHT FORWARD|BALANCE CARRIED FORWARD"
        )
        df = df[~desc.str.contains(pattern, regex=True, na=False)]

    for col in ["No.", "Transaction Amount(INR)"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="ignore")

    return df.drop_duplicates().reset_index(drop=True)

def clean_raw_bank_statement_axis(path):
    def _extract_table_from_raw(raw: pd.DataFrame):
        if raw.dropna(how="all").empty:
            return None

        header_row_idx = None
        for i, row in raw.iterrows():
            vals = [str(v).strip() for v in row.tolist() if pd.notna(v)]
            upper_vals = [v.upper() for v in vals]

            if (
                any(v == "S.NO" for v in upper_vals)
                and any("TRANSACTION DATE" in v for v in upper_vals)
                and any("PARTICULARS" in v for v in upper_vals)
                and any("AMOUNT(INR)" in v or "TRANSACTION AMOUNT" in v for v in upper_vals)
                and any("DEBIT/CREDIT" in v for v in upper_vals)
            ):
                header_row_idx = i
                break

        if header_row_idx is None:
            return None

        header_vals = [str(x).strip() for x in raw.iloc[header_row_idx].tolist()]
        df = raw.iloc[header_row_idx + 1:].copy()

        if df.shape[1] < len(header_vals):
            for _ in range(len(header_vals) - df.shape[1]):
                df[df.shape[1]] = np.nan

        df = df.iloc[:, :len(header_vals)]
        df.columns = header_vals
        return df

    path = Path(path)
    ext = path.suffix.lower()
    tables = []

    if ext in [".xlsx", ".xls", ".xlsm"]:
        xls = pd.ExcelFile(path)
        for sheet in xls.sheet_names:
            raw = xls.parse(sheet_name=sheet, header=None)
            tbl = _extract_table_from_raw(raw)
            if tbl is not None:
                tables.append(tbl)

    elif ext == ".csv":
        raw = pd.read_csv(path, header=None)
        tbl = _extract_table_from_raw(raw)
        if tbl is not None:
            tables.append(tbl)

    else:
        try:
            raw = pd.read_excel(path, header=None)
        except Exception:
            raw = pd.read_csv(path, header=None)
        tbl = _extract_table_from_raw(raw)
        if tbl is not None:
            tables.append(tbl)

    if not tables:
        raise ValueError("Axis bank parser: No usable transaction table found.")

    df_all = pd.concat(tables, ignore_index=True)

    orig_to_canon = {
        "S.No": "No.",
        "Transaction Date (dd/mm/yyyy)": "Txn Posted Date",
        "Value Date (dd/mm/yyyy)": "Value Date",
        "Particulars": "Description",
        "Amount(INR)": "Transaction Amount(INR)",
        "Transaction Amount(INR)": "Transaction Amount(INR)",
        "Debit/Credit": "Cr/Dr",
        "Balance(INR)": "Balance(INR)",
        "Cheque Number": "Cheque Number",
        "Branch Name(SOL)": "Branch Name(SOL)",
    }

    canon_cols_order = [
        "No.",
        "Txn Posted Date",
        "Value Date",
        "Description",
        "Cr/Dr",
        "Transaction Amount(INR)",
        "Balance(INR)",
        "Cheque Number",
        "Branch Name(SOL)",
    ]

    col_map = {}
    for col in df_all.columns:
        if col in orig_to_canon:
            col_map[col] = orig_to_canon[col]

    canon_df = pd.DataFrame()
    for canon in canon_cols_order:
        sources = [src for src, tgt in col_map.items() if tgt == canon]
        if sources:
            canon_df[canon] = df_all[sources[0]]
        else:
            canon_df[canon] = np.nan

    canon_df = canon_df.dropna(how="all")
    canon_df = canon_df.loc[:, ~canon_df.columns.duplicated()].copy()

    def _is_repeated_header(row):
        for c in canon_cols_order:
            val = str(row[c]).strip()
            if val == "" and canon_df[c].isna().all():
                continue
            if val == c:
                continue
            else:
                return False
        return True

    if not canon_df.empty:
        mask_header = canon_df.apply(_is_repeated_header, axis=1)
        canon_df = canon_df[~mask_header]

    if "Description" in canon_df.columns:
        desc_upper = canon_df["Description"].astype(str).str.upper()
        pattern = (
            r"OPENING BALANCE|CLOSING BALANCE|"
            r"BALANCE BROUGHT FORWARD|BALANCE CARRIED FORWARD|TRANSACTION TOTAL|TOTAL"
        )
        canon_df = canon_df[~desc_upper.str.contains(pattern, regex=True, na=False)]

    def _empty(x):
        s = str(x).strip().lower()
        return s in ("", "nan", "none")

    def _is_noise(row):
        return (
            _empty(row.get("Txn Posted Date"))
            and _empty(row.get("Description"))
            and _empty(row.get("Transaction Amount(INR)"))
        )

    if not canon_df.empty:
        noise_mask = canon_df.apply(_is_noise, axis=1)
        canon_df = canon_df[~noise_mask]

    for col in ["Transaction Amount(INR)", "Balance(INR)"]:
        if col in canon_df.columns:
            canon_df[col] = (
                canon_df[col]
                .astype(str)
                .str.replace(",", "", regex=False)
                .str.strip()
            )
            canon_df[col] = pd.to_numeric(canon_df[col], errors="ignore")

    if "No." in canon_df.columns:
        canon_df["No."] = pd.to_numeric(
            canon_df["No."].astype(str).str.strip(), errors="ignore"
        )

    canon_df = canon_df.drop_duplicates().reset_index(drop=True)
    return canon_df

# ==========================================
#  BANK TYPE AUTO-DETECTION (WORKING)
# ==========================================

def detect_bank_type(bank_path: Path) -> str:
    bank_path = Path(bank_path)
    ext = bank_path.suffix.lower()

    def _row_tokens(row) -> set:
        toks = set()
        for v in row:
            if pd.isna(v):
                continue
            s = str(v).strip()
            if s:
                toks.add(s)
                toks.add(s.upper())
        return toks

    def _scan_raw(raw: pd.DataFrame) -> Optional[str]:
        n = min(len(raw), 120)
        for i in range(n):
            tokens = _row_tokens(raw.iloc[i].tolist())

            if ("Transaction ID" in tokens) and ("Description" in tokens):
                return "ICICI"

            up = {t.upper() for t in tokens}
            axis_hit = (
                ("S.NO" in up) and
                ("PARTICULARS" in up) and
                ("DEBIT/CREDIT" in up)
            )
            if axis_hit:
                return "AXIS"

            axis_hit2 = (
                ("S.NO" in up) and
                ("PARTICULARS" in up) and
                ("DEBIT/CREDIT" in up) and
                (any("TRANSACTION DATE" in t for t in up)) and
                (any("AMOUNT(INR)" in t or "TRANSACTION AMOUNT" in t for t in up))
            )
            if axis_hit2:
                return "AXIS"

        return None

    if ext in [".xlsx", ".xls", ".xlsm"]:
        xls = pd.ExcelFile(bank_path)
        for sh in xls.sheet_names:
            raw = xls.parse(sh, header=None)
            bt = _scan_raw(raw)
            if bt:
                return bt

    elif ext == ".csv":
        raw = pd.read_csv(bank_path, header=None)
        bt = _scan_raw(raw)
        if bt:
            return bt

    else:
        try:
            raw = pd.read_excel(bank_path, header=None)
        except Exception:
            raw = pd.read_csv(bank_path, header=None)
        bt = _scan_raw(raw)
        if bt:
            return bt

    raise ValueError(
        "Could not auto-detect bank type from file headers. "
        "Expected ICICI headers like 'Transaction ID' + 'Description' "
        "or AXIS headers like 'S.No' + 'Particulars' + 'Debit/Credit'."
    )

# ==========================================
#  TPA TYPE AUTO-DETECTION (RHS-ONLY, UNIQUE PAIR, FAIL-FAST)
# ==========================================

def detect_tpa_choice(mis_path: Path, scan_rows: int = 120) -> str:
    mis_path = Path(mis_path)
    ext = mis_path.suffix.lower()

    def _norm_hdr(x: str) -> str:
        return re.sub(r"[^A-Z0-9]", "", str(x).upper()).strip()

    def _best_header_tokens_for_raw(raw: pd.DataFrame) -> Optional[set]:
        best_i, best_hits = None, -1
        n = min(len(raw), scan_rows)

        for i in range(n):
            row1 = raw.iloc[i].tolist()
            row2 = raw.iloc[i + 1].tolist() if i + 1 < len(raw) else []
            toks = []
            toks.extend(row1)
            toks.extend(row2)
            tokens = {_norm_hdr(v) for v in toks if pd.notna(v) and str(v).strip() != ""}

            hits = 0
            for t in tokens:
                if t:
                    hits += 1
            if hits > best_hits:
                best_hits = hits
                best_i = i

        if best_i is None:
            return None

        row1 = raw.iloc[best_i].tolist()
        row2 = raw.iloc[best_i + 1].tolist() if best_i + 1 < len(raw) else []
        toks = []
        toks.extend(row1)
        toks.extend(row2)
        tokens = {_norm_hdr(v) for v in toks if pd.notna(v) and str(v).strip() != ""}
        if not tokens:
            return None
        return tokens

    raws = []
    if ext in [".xlsx", ".xls", ".xlsm"]:
        xls = pd.ExcelFile(mis_path)
        for sh in xls.sheet_names:
            raws.append(xls.parse(sh, header=None, dtype=str))
    elif ext == ".csv":
        raws.append(pd.read_csv(mis_path, header=None, dtype=str))
    else:
        try:
            raws.append(pd.read_excel(mis_path, header=None, dtype=str))
        except Exception:
            raws.append(pd.read_csv(mis_path, header=None, dtype=str))

    header_tokens = None
    best_token_count = -1
    for raw in raws:
        tokens = _best_header_tokens_for_raw(raw)
        if tokens and len(tokens) > best_token_count:
            header_tokens = tokens
            best_token_count = len(tokens)

    if not header_tokens:
        raise ValueError("TPA auto-detect failed: could not locate any recognizable header row.")

    candidates = []
    tpa_mis_maps = get_tpa_mis_maps()
    for tpa_name, mp in tpa_mis_maps.items():
        rhs_utr = _norm_hdr(mp["Cheque/ NEFT/ UTR No."])
        rhs_clm = _norm_hdr(mp["Claim No"])
        if (rhs_utr in header_tokens) and (rhs_clm in header_tokens):
            candidates.append(tpa_name)

    if len(candidates) == 1:
        return candidates[0]

    if len(candidates) == 0:
        raise ValueError(
            "TPA auto-detect failed: no TPA matched the unique RHS pair "
            "(UTR RHS + Claim RHS) in the detected header."
        )

    raise ValueError(
        "TPA auto-detect failed: ambiguous. The same RHS pair matched multiple TPAs: "
        f"{candidates}"
    )

# ==========================================
#  PART 3: MIS PARSING + BANK↔MIS MATCHING
# ==========================================

def parse_mis_universal(
    mis_path,
    tpa_name: str = "IHX (Original MIS)",
    empty_threshold: float = 0.5
) -> pd.DataFrame:

    mis_path = Path(mis_path)
    ext = mis_path.suffix.lower()

    tpa_mis_maps = get_tpa_mis_maps()
    if tpa_name not in tpa_mis_maps:
        raise ValueError(f"Unknown TPA '{tpa_name}' for MIS parsing.")

    mapping: Dict[str, str] = tpa_mis_maps[tpa_name]
    expected_sources = list(mapping.values())
    canonical_names = list(mapping.keys())

    def _norm_local(s: str) -> str:
        return re.sub(r"[^A-Z0-9]", "", str(s).upper())

    expected_norm = {_norm_local(x) for x in expected_sources + canonical_names}

    def _hunt_header(raw: pd.DataFrame) -> Optional[int]:
        best_idx, best_score = None, -999
        for i in range(min(80, len(raw))):
            row1 = raw.iloc[i].tolist()
            row2 = raw.iloc[i + 1].tolist() if i + 1 < len(raw) else []
            merged = []
            merged.extend(row1)
            merged.extend(row2)

            hits = 0
            for v in merged:
                if _norm_local(v) in expected_norm:
                    hits += 1

            if hits > best_score:
                best_idx, best_score = i, hits

        if best_idx is None or best_score < 1:
            return None
        return best_idx

    def _row_is_noise(row: pd.Series, important_idx, empty_threshold: float) -> bool:
        vals = [str(v).strip() for v in row.tolist()]
        n_cols = len(vals)
        empties = sum(v.lower() in ("", "nan", "none") for v in vals)
        empty_ratio = empties / max(1, n_cols)

        if empty_ratio < empty_threshold:
            return False

        if important_idx:
            if all(vals[i].lower() in ("", "nan", "none") for i in important_idx):
                return True
            return False

        return True

    def _extract_from_sheet(raw: pd.DataFrame) -> Optional[pd.DataFrame]:
        if raw.dropna(how="all").empty:
            return None

        header_idx = _hunt_header(raw)
        if header_idx is None:
            return None

        header_row_1 = raw.iloc[header_idx].tolist()
        header_row_2 = raw.iloc[header_idx + 1].tolist() if header_idx + 1 < len(raw) else []

        header_vals = []
        for j in range(max(len(header_row_1), len(header_row_2))):
            h1 = str(header_row_1[j]).strip() if j < len(header_row_1) and pd.notna(header_row_1[j]) else ""
            h2 = str(header_row_2[j]).strip() if j < len(header_row_2) and pd.notna(header_row_2[j]) else ""
            if h1 and h1.lower() not in ("nan", "none"):
                header_vals.append(h1)
            else:
                header_vals.append(h2)

        df_sheet = raw.iloc[header_idx + 1:].copy()

        if df_sheet.shape[1] < len(header_vals):
            for _ in range(len(header_vals) - df_sheet.shape[1]):
                df_sheet[df_sheet.shape[1]] = np.nan
        df_sheet = df_sheet.iloc[:, :len(header_vals)]
        df_sheet.columns = header_vals

        def _is_header_like(row: pd.Series) -> bool:
            vals = [str(x).strip() for x in row.tolist()]
            return vals[:len(header_vals)] == header_vals

        df_sheet = df_sheet[~df_sheet.apply(_is_header_like, axis=1)]

        df_sheet.columns = _make_unique_columns(df_sheet.columns)
        df_sheet = df_sheet.dropna(how="all")

        for c in df_sheet.columns:
            df_sheet[c] = (
                _force_series(df_sheet[c])
                .astype(str)
                .str.replace("\xa0", " ", regex=False)
                .str.strip()
            )

        important_idx = []
        for i, col in enumerate(df_sheet.columns):
            if col in expected_sources or col in canonical_names:
                important_idx.append(i)

        noise_mask = df_sheet.apply(
            lambda r: _row_is_noise(r, important_idx, empty_threshold),
            axis=1
        )
        df_sheet = df_sheet[~noise_mask]

        return df_sheet.reset_index(drop=True)

    tables = []

    if ext in [".xlsx", ".xls", ".xlsm"]:
        xls = pd.ExcelFile(mis_path)
        for sh in xls.sheet_names:
            raw = xls.parse(sh, header=None, dtype=str)
            tbl = _extract_from_sheet(raw)
            if tbl is not None:
                tables.append(tbl)

    elif ext == ".csv":
        raw = pd.read_csv(mis_path, header=None, dtype=str)
        tbl = _extract_from_sheet(raw)
        if tbl is not None:
            tables.append(tbl)

    else:
        try:
            raw = pd.read_excel(mis_path, header=None, dtype=str)
        except Exception:
            raw = pd.read_csv(mis_path, header=None, dtype=str)
        tbl = _extract_from_sheet(raw)
        if tbl is not None:
            tables.append(tbl)

    if not tables:
        raise ValueError("Universal MIS parser: No table detected for this TPA in any sheet.")

    final = pd.concat(tables, ignore_index=True)
    return final.reset_index(drop=True)

def step2_match_bank_mis_by_utr(bank_df: pd.DataFrame,
                               mis_df: pd.DataFrame,
                               tpa_name: str,
                               deduplicate: bool = True,
                               min_key_len: int = 8):

    if bank_df.empty:
        return pd.DataFrame(), bank_df
    if mis_df.empty:
        return pd.DataFrame(), bank_df

    bank_df = bank_df.loc[:, ~bank_df.columns.duplicated()].copy()

    tpa_mis_maps = get_tpa_mis_maps()
    mapping = tpa_mis_maps.get(tpa_name)
    if mapping is None:
        raise ValueError(f"Unknown TPA '{tpa_name}' for MIS mapping.")

    actual_lookup = {}
    for c in mis_df.columns:
        k = _norm_colname(c)
        if k and (k not in actual_lookup):
            actual_lookup[k] = c

    rename_map = {}
    for canon_col, src_col in mapping.items():
        key = _norm_colname(src_col)
        if key in actual_lookup:
            rename_map[actual_lookup[key]] = canon_col

    mis_std = mis_df.rename(columns=rename_map).copy()

    if "Cheque/ NEFT/ UTR No." not in mis_std.columns:
        raise ValueError(
            f"MIS mapping failed: could not find UTR column after rename for TPA '{tpa_name}'. "
            f"Expected source column '{mapping.get('Cheque/ NEFT/ UTR No.')}'."
        )

    if "Claim No" not in mis_std.columns:
        raise ValueError(
            f"MIS mapping failed: could not find Claim No column after rename for TPA '{tpa_name}'. "
            f"Expected source column '{mapping.get('Claim No')}'."
        )

    mis_std["Cheque/ NEFT/ UTR No."] = _clean_key_series(mis_std["Cheque/ NEFT/ UTR No."])
    mis_std["Claim No"] = _clean_key_series(mis_std["Claim No"])

    # exact full UTR matching only; no truncation
    mis_std["_UTR_SEARCH"] = _clean_key_series(mis_std["Cheque/ NEFT/ UTR No."])
    mis_std["_CLAIM_SEARCH"] = _clean_key_series(mis_std["Claim No"])

    mis_std["_PAIR_KEY_RAW"] = mis_std.apply(
        lambda r: _pair_key_raw(r.get("Cheque/ NEFT/ UTR No."), r.get("Claim No")),
        axis=1
    )
    mis_std["_PAIR_KEY"] = mis_std.apply(
        lambda r: _pair_key_clean(r.get("_UTR_SEARCH"), r.get("_CLAIM_SEARCH")),
        axis=1
    )
    mis_std["_MIS_ROW_ID"] = np.arange(len(mis_std))

    pairs = mis_std[["_UTR_SEARCH", "Claim No", "_CLAIM_SEARCH", "_PAIR_KEY_RAW", "_PAIR_KEY", "_MIS_ROW_ID"]].copy()
    pairs = pairs.dropna(subset=["_UTR_SEARCH"])
    pairs["_UTR_SEARCH"] = pairs["_UTR_SEARCH"].astype(str).map(str.strip)
    pairs["Claim No"] = pairs["Claim No"].astype(str).map(str.strip)
    pairs["_CLAIM_SEARCH"] = pairs["_CLAIM_SEARCH"].astype(str).map(str.strip)
    pairs = pairs.drop_duplicates()

    pairs = pairs[pairs["_UTR_SEARCH"].map(lambda x: len(str(x)) >= int(min_key_len))]

    col_to_search = "Description" if "Description" in bank_df.columns else bank_df.columns[1]
    parts = []

    bank_df = bank_df.copy().reset_index(drop=True)
    bank_df["_BANK_ROW_ID"] = np.arange(len(bank_df))

    bank_text = _force_series(bank_df[col_to_search]).astype(str)
    utr_keys = pairs["_UTR_SEARCH"].dropna().astype(str).map(str.strip).unique()

    for utr in utr_keys:
        s = utr.strip()
        if not s:
            continue

        m = bank_text.str.contains(s, regex=False, na=False)
        if m.any():
            t = bank_df.loc[m].copy()
            t["Matched_Key"] = s
            parts.append(t)

    if not parts:
        return pd.DataFrame(), bank_df.drop(columns=["_BANK_ROW_ID"], errors="ignore")

    matched_bank = pd.concat(parts, ignore_index=True)

    merged = matched_bank.merge(
        mis_std,
        left_on="Matched_Key",
        right_on="_UTR_SEARCH",
        how="inner",
        suffixes=("_bank", "_mis"),
    )

    merged["UTR_RAW"] = merged["Cheque/ NEFT/ UTR No."]
    merged["CLAIM_RAW"] = merged["Claim No"]
    merged["UTR_KEY"] = merged["_UTR_SEARCH"]
    merged["CLAIM_KEY"] = merged["_CLAIM_SEARCH"]
    merged["PAIR_KEY_RAW"] = merged["_PAIR_KEY_RAW"]
    merged["PAIR_KEY"] = merged["_PAIR_KEY"]

    if deduplicate:
        merged = merged.drop_duplicates()

    merged_text_col = col_to_search
    if merged_text_col not in merged.columns and f"{merged_text_col}_bank" in merged.columns:
        merged_text_col = f"{merged_text_col}_bank"

    if "Transaction ID" in bank_df.columns:
        merged_tid_col = "Transaction ID"
        if merged_tid_col not in merged.columns and f"{merged_tid_col}_bank" in merged.columns:
            merged_tid_col = f"{merged_tid_col}_bank"

        if merged_tid_col in merged.columns:
            not_in = bank_df.loc[~bank_df["Transaction ID"].isin(merged[merged_tid_col])]
        else:
            not_in = bank_df.loc[~bank_df[col_to_search].isin(merged[merged_text_col])]
    else:
        not_in = bank_df.loc[~bank_df[col_to_search].isin(merged[merged_text_col])]

    not_in = not_in.drop(columns=["_BANK_ROW_ID"], errors="ignore")

    return merged.reset_index(drop=True), not_in

# ==========================================
#  PART 3B: OUTSTANDING PARSER + INSURANCE COMPANY
# ==========================================

_FOOTER_TOKENS = ["SUB TOTAL", "SUBTOTAL", "TOTAL", "GRAND TOTAL"]

_OUT_HEADER_KEYS = [
    "Sl No", "Bill No", "Date", "CR No", "Patient Name",
    "Net Amount", "Amount Paid", "TDS", "Write-Off",
    "Balance", "Location", "Consultant", "Claim No", "Insurance Company"
]

def _hunt_outstanding_header_row(df_raw: pd.DataFrame) -> int:
    norm = lambda s: re.sub(r"[^A-Z]", "", str(s).upper())
    targets = [norm(k) for k in _OUT_HEADER_KEYS]
    best_idx, best_hits = None, -1
    for i in range(min(len(df_raw), 60)):
        row = df_raw.iloc[i].fillna("").astype(str).tolist()
        hits = 0
        for cell in row:
            nc = norm(cell)
            if nc in targets or (nc.startswith("CONSUL") and "CONSULTANT" in targets):
                hits += 1
        if best_hits is None or hits > best_hits:
            best_idx, best_hits = i, hits
    if best_idx is None or best_hits <= 2:
        raise ValueError("Outstanding parser: could not confidently locate header row.")
    return best_idx

def _row_is_section_header_like(row: pd.Series) -> bool:
    vals = row.fillna("").astype(str).tolist()
    if not vals:
        return False
    col0 = vals[0].strip()
    others_empty = all((str(v).strip() == "") for v in vals[1:])
    return bool(col0) and others_empty

def _clean_entity_name(text: str) -> str:
    s = (text or "").replace("\xa0", " ").strip()
    s = re.sub(r"^\s*\d+\s*", "", s)
    return re.sub(r"\s+", " ", s)

def _row_is_footer_like(row: pd.Series) -> bool:
    flat = " ".join([str(x) for x in row.fillna("").tolist()]).upper()
    return any(tok in flat for tok in _FOOTER_TOKENS)

def parse_outstanding_excel_to_clean(xlsx_path: Path) -> pd.DataFrame:
    raw = pd.read_excel(xlsx_path, header=None, dtype=str)
    hdr_idx = _hunt_outstanding_header_row(raw)
    header_vals = [str(x).strip() for x in raw.iloc[hdr_idx].tolist()]

    header_norm = []
    for h in header_vals:
        hn = str(h).strip()
        if re.sub(r"[^A-Za-z]", "", hn).lower().startswith("consul"):
            hn = "Consultant"
        if hn.strip().lower() == "insurance companies":
            hn = "Insurance Company"
        header_norm.append(hn)

    df = raw.iloc[hdr_idx + 1:].copy()
    if df.shape[1] < len(header_norm):
        for _ in range(len(header_norm) - df.shape[1]):
            df[df.shape[1]] = ""
    df = df.iloc[:, :len(header_norm)]
    df.columns = header_norm

    ent_col = []
    current_entity = ""
    header_row_indices = []
    for idx, row in df.iterrows():
        if _row_is_section_header_like(row):
            current_entity = _clean_entity_name(row.iloc[0])
            header_row_indices.append(idx)
        ent_col.append(current_entity)
    df["Bill Company Name"] = ent_col

    if header_row_indices:
        df = df.drop(index=header_row_indices)

    df = df[~df.apply(_row_is_footer_like, axis=1)]

    for c in df.columns:
        df[c] = df[c].astype(str).str.replace("\xa0", " ", regex=False).str.strip()

    for col in ["Patient Name", "CR No", "Balance"]:
        if col not in df.columns:
            raise ValueError(f"Outstanding parser: missing required column '{col}' after parsing.")

    return df.reset_index(drop=True)

def _get_outstanding_clean(outstanding_input) -> pd.DataFrame:
    """
    Accept either:
    - Path / str to outstanding file
    - already-cleaned outstanding DataFrame

    Returns a safe copy.
    """
    if isinstance(outstanding_input, pd.DataFrame):
        return outstanding_input.copy()
    return parse_outstanding_excel_to_clean(Path(outstanding_input))

# ==========================================
#  PART 4: CLAIM MATCH HELPERS (STRICT KEYS)
# ==========================================

_SEP_RE = re.compile(r"[\s\-_]+")
_NONALNUM_RE = re.compile(r"[^A-Z0-9]")

_PAREN_RE = re.compile(r"\([^)]*\)")
_DOT_RE = re.compile(r"\..*$")
_SUFFIX_RE = re.compile(r"([_-])(\d{1,2})$")

def _strip_trailing_suffix(s: str) -> str:
    m = _SUFFIX_RE.search(s)
    if not m:
        return s
    n = int(m.group(2))
    if 0 <= n <= 20:
        return s[:m.start()]
    return s

def _md_canon(s: str) -> str:
    if s.startswith("MDI1"):
        return "MD1" + s[4:]
    if s.startswith("MDI"):
        return "MD1" + s[3:]
    return s

def _alpha_key(val) -> str:
    if pd.isna(val):
        return ""
    s = str(val).replace("\xa0", " ").strip().upper()
    if s.lower() in ['nan', 'none', 'null', 'na', 'n/a', '']:
        return ""
    if s.endswith(".0"):
        s = s[:-2]

    s = _PAREN_RE.sub("", s)
    s = _DOT_RE.sub("", s)
    s = _strip_trailing_suffix(s)

    s = _SEP_RE.sub("", s)
    s = _md_canon(s)
    s = _NONALNUM_RE.sub("", s)
    return s

def _split_tokens_any(s: str) -> List[str]:
    if s is None:
        return []
    x = str(s).replace("\xa0", " ").strip()
    if x.strip().lower() in ['nan', 'none', 'null', 'na', 'n/a', '']:
        return []
    x = re.sub(r"\bAND\b", "/", x, flags=re.IGNORECASE)
    parts = [p.strip() for p in re.split(r"[/,&]", x) if p.strip()]
    return parts

def _numeric_tokens_from_parts(parts: List[str], min_len: int = 6) -> List[str]:
    toks = []
    for p in parts:
        p = _strip_trailing_suffix(p.strip())
        nums = re.findall(rf"\d{{{min_len},}}", p)
        toks.extend(nums)
    return toks

def _alpha_tokens_from_parts(parts: List[str]) -> List[str]:
    toks = []
    for p in parts:
        k = _alpha_key(p)
        if k:
            toks.append(k)
    return toks

# ==========================================
#  PART 4A: IHX STRICT MATCH (UNCHANGED BEHAVIOR)
# ==========================================

def step4_strict_matches(step3_df: pd.DataFrame,
                         outstanding_path: Path,
                         deduplicate: bool = True,
                         keep_internal: bool = False):

    if step3_df.empty:
        return pd.DataFrame(), pd.DataFrame()
    if "Claim No" not in step3_df.columns:
        raise ValueError("Step 3 missing Claim No")

    out = _get_outstanding_clean(outstanding_path)

    if "Claim No" in out.columns:
        out = out.rename(columns={"Claim No": "Claim No_out"})

    for col in ["Patient Name", "CR No", "Balance"]:
        if col not in out.columns:
            raise ValueError(f"Outstanding missing '{col}'.")

    L = out.copy().reset_index(drop=False).rename(columns={"index": "_OUT_IDX"})
    R = step3_df.copy().reset_index(drop=True)

    if "_STEP3_ROW_ID" not in R.columns:
        R["_STEP3_ROW_ID"] = np.arange(len(R))

    R["_RID"] = np.arange(len(R))
    L["_ALPHA_KEY"] = L.get("Claim No_out", "").apply(_alpha_key)
    R["_ALPHA_KEY"] = R["Claim No"].apply(_alpha_key)

    L_alpha = L[L["_ALPHA_KEY"] != ""].copy()
    R_alpha = R[R["_ALPHA_KEY"] != ""].copy()

    merged_alpha = L_alpha.merge(
        R_alpha,
        on="_ALPHA_KEY",
        how="inner",
        suffixes=("_out", "_m3")
    )
    merged_alpha["MATCH_MODE"] = "ALPHA_STRICT"

    matched = merged_alpha.copy()

    if deduplicate and not matched.empty:
        matched = matched.drop_duplicates()

    matched_rids = set(matched["_RID"].unique().tolist()) if (not matched.empty and "_RID" in matched.columns) else set()
    unmatched_step3 = R[~R["_RID"].isin(matched_rids)].copy()

    drop_cols_R = [c for c in ["_RID", "_ALPHA_KEY"] if c in unmatched_step3.columns]
    if drop_cols_R:
        unmatched_step3 = unmatched_step3.drop(columns=drop_cols_R)

    if not keep_internal:
        drop_cols_matched = [c for c in ["_OUT_IDX", "_ALPHA_KEY", "_RID"] if c in matched.columns]
        if drop_cols_matched:
            matched = matched.drop(columns=drop_cols_matched)

    return matched.reset_index(drop=True), unmatched_step3.reset_index(drop=True)

# ==========================================
#  PART 4B: NON-IHX ALPHA STRICT UNIQUE (TPA-GATED)
# ==========================================

def step4_alpha_strict_unique(step3_df: pd.DataFrame,
                              outstanding_path: Path,
                              deduplicate: bool = True,
                              match_mode: str = "ALPHA_STRICT_UNIQUE",
                              keep_internal: bool = False):

    if step3_df.empty:
        return pd.DataFrame(), pd.DataFrame()
    if "Claim No" not in step3_df.columns:
        raise ValueError("Step 3 missing Claim No")

    out = _get_outstanding_clean(outstanding_path)
    if "Claim No" in out.columns:
        out = out.rename(columns={"Claim No": "Claim No_out"})

    L = out.copy().reset_index(drop=False).rename(columns={"index": "_OUT_IDX"})
    R = step3_df.copy().reset_index(drop=True)

    if "_STEP3_ROW_ID" not in R.columns:
        R["_STEP3_ROW_ID"] = np.arange(len(R))

    R["_RID"] = np.arange(len(R))

    L["_ALPHA_KEY"] = L.get("Claim No_out", "").apply(_alpha_key)
    R["_ALPHA_KEY"] = R["Claim No"].apply(_alpha_key)

    L = L[L["_ALPHA_KEY"] != ""].copy()
    R = R[R["_ALPHA_KEY"] != ""].copy()

    if L.empty or R.empty:
        return pd.DataFrame(), step3_df

    l_counts = L["_ALPHA_KEY"].value_counts()
    r_counts = R["_ALPHA_KEY"].value_counts()

    ok_keys = set(l_counts[l_counts == 1].index).intersection(set(r_counts[r_counts == 1].index))
    if not ok_keys:
        return pd.DataFrame(), step3_df

    L1 = L[L["_ALPHA_KEY"].isin(ok_keys)].copy()
    R1 = R[R["_ALPHA_KEY"].isin(ok_keys)].copy()

    merged = L1.merge(R1, on="_ALPHA_KEY", how="inner", suffixes=("_out", "_m3"))
    merged["MATCH_MODE"] = match_mode

    if deduplicate and not merged.empty:
        merged = merged.drop_duplicates()

    matched_rids = set(merged["_RID"].unique().tolist()) if (not merged.empty and "_RID" in merged.columns) else set()
    unmatched = R[~R["_RID"].isin(matched_rids)].copy()

    unmatched = unmatched.drop(columns=["_RID", "_ALPHA_KEY"], errors="ignore")
    if not keep_internal:
        merged = merged.drop(columns=["_OUT_IDX", "_RID", "_ALPHA_KEY"], errors="ignore")

    return merged.reset_index(drop=True), unmatched.reset_index(drop=True)

# ==========================================
#  PART 4C: NON-IHX SPLIT-ALPHA UNIQUE (VIDAL)
# ==========================================

def step4_split_alpha_unique(step3_df: pd.DataFrame,
                             outstanding_path: Path,
                             deduplicate: bool = True,
                             match_mode: str = "SPLIT_ALPHA_UNIQUE",
                             keep_internal: bool = False):

    if step3_df.empty:
        return pd.DataFrame(), pd.DataFrame()
    if "Claim No" not in step3_df.columns:
        raise ValueError("Step 3 missing Claim No")

    out = _get_outstanding_clean(outstanding_path)
    if "Claim No" in out.columns:
        out = out.rename(columns={"Claim No": "Claim No_out"})

    L = out.copy().reset_index(drop=False).rename(columns={"index": "_OUT_IDX"}).copy()
    R = step3_df.copy().reset_index(drop=True).copy()

    if "_STEP3_ROW_ID" not in R.columns:
        R["_STEP3_ROW_ID"] = np.arange(len(R))

    R["_RID"] = np.arange(len(R))

    R["_ALPHA_KEY"] = R["Claim No"].apply(_alpha_key)
    R = R[R["_ALPHA_KEY"] != ""].copy()
    if R.empty:
        return pd.DataFrame(), step3_df

    key_to_rids = R.groupby("_ALPHA_KEY")["_RID"].apply(lambda x: set(x.tolist())).to_dict()

    picks = []
    for _, row in L.iterrows():
        parts = _split_tokens_any(row.get("Claim No_out", ""))
        toks = _alpha_tokens_from_parts(parts)
        if not toks:
            continue

        cand = set()
        ambiguous = False
        for t in toks:
            rids = key_to_rids.get(str(t).strip())
            if not rids:
                continue
            cand |= rids
            if len(rids) > 1:
                ambiguous = True

        if ambiguous:
            continue
        if len(cand) == 1:
            picks.append({"_OUT_IDX": row["_OUT_IDX"], "_RID": list(cand)[0]})

    if not picks:
        return pd.DataFrame(), step3_df

    P = pd.DataFrame(picks).drop_duplicates(subset=["_OUT_IDX"])
    grp = P.groupby("_OUT_IDX")["_RID"].nunique().reset_index(name="_N")
    ok_out = set(grp.loc[grp["_N"] == 1, "_OUT_IDX"].tolist())
    P = P[P["_OUT_IDX"].isin(ok_out)].copy()

    L_pick = L.merge(P, on="_OUT_IDX", how="inner")
    merged = L_pick.merge(R, on="_RID", how="inner", suffixes=("_out", "_m3"))
    merged["MATCH_MODE"] = match_mode

    if deduplicate and not merged.empty:
        merged = merged.drop_duplicates()

    matched_rids = set(merged["_RID"].unique().tolist()) if (not merged.empty and "_RID" in merged.columns) else set()
    remaining = R[~R["_RID"].isin(matched_rids)].copy()

    remaining = remaining.drop(columns=["_RID", "_ALPHA_KEY"], errors="ignore")
    if not keep_internal:
        merged = merged.drop(columns=["_OUT_IDX", "_RID", "_ALPHA_KEY"], errors="ignore")

    return merged.reset_index(drop=True), remaining.reset_index(drop=True)

# ==========================================
#  PART 4D: NON-IHX NUMERIC SPLIT UNIQUE (GOOD HEALTH / VOLO / SBI)
# ==========================================

def step4_numeric_split_unique(step3_df: pd.DataFrame,
                               outstanding_path: Path,
                               deduplicate: bool = True,
                               match_mode: str = "NUMERIC_SPLIT_UNIQUE",
                               min_len: int = 6,
                               keep_internal: bool = False):

    if step3_df.empty:
        return pd.DataFrame(), pd.DataFrame()
    if "Claim No" not in step3_df.columns:
        raise ValueError("Step 3 missing Claim No")

    out = _get_outstanding_clean(outstanding_path)
    if "Claim No" in out.columns:
        out = out.rename(columns={"Claim No": "Claim No_out"})

    L = out.copy().reset_index(drop=False).rename(columns={"index": "_OUT_IDX"}).copy()
    R = step3_df.copy().reset_index(drop=True).copy()

    if "_STEP3_ROW_ID" not in R.columns:
        R["_STEP3_ROW_ID"] = np.arange(len(R))

    R["_RID"] = np.arange(len(R))

    def _mis_nums(val):
        parts = _split_tokens_any(val)
        nums = _numeric_tokens_from_parts(parts, min_len=min_len)
        return nums

    R["_NUMS"] = R["Claim No"].apply(_mis_nums)
    R_exp = R[["_RID", "_NUMS"]].explode("_NUMS").dropna()
    R_exp["_NUMS"] = R_exp["_NUMS"].astype(str).str.strip()
    R_exp = R_exp[R_exp["_NUMS"] != ""].drop_duplicates()

    if R_exp.empty:
        R = R.drop(columns=["_RID", "_NUMS"], errors="ignore")
        return pd.DataFrame(), step3_df

    tok_to_rids = R_exp.groupby("_NUMS")["_RID"].apply(lambda x: set(x.tolist())).to_dict()

    picks = []
    for _, row in L.iterrows():
        parts = _split_tokens_any(row.get("Claim No_out", ""))
        toks = _numeric_tokens_from_parts(parts, min_len=min_len)
        if not toks:
            continue

        cand = set()
        ambiguous = False
        for t in toks:
            rids = tok_to_rids.get(str(t).strip())
            if not rids:
                continue
            cand |= rids
            if len(rids) > 1:
                ambiguous = True

        if ambiguous:
            continue
        if len(cand) == 1:
            picks.append({"_OUT_IDX": row["_OUT_IDX"], "_RID": list(cand)[0]})

    if not picks:
        return pd.DataFrame(), step3_df

    P = pd.DataFrame(picks).drop_duplicates(subset=["_OUT_IDX"])
    grp = P.groupby("_OUT_IDX")["_RID"].nunique().reset_index(name="_N")
    ok_out = set(grp.loc[grp["_N"] == 1, "_OUT_IDX"].tolist())
    P = P[P["_OUT_IDX"].isin(ok_out)].copy()

    L_pick = L.merge(P, on="_OUT_IDX", how="inner")
    merged = L_pick.merge(R, on="_RID", how="inner", suffixes=("_out", "_m3"))
    merged["MATCH_MODE"] = match_mode

    if deduplicate and not merged.empty:
        merged = merged.drop_duplicates()

    matched_rids = set(merged["_RID"].unique().tolist()) if (not merged.empty and "_RID" in merged.columns) else set()
    remaining = R[~R["_RID"].isin(matched_rids)].copy()

    remaining = remaining.drop(columns=["_RID", "_NUMS"], errors="ignore")
    if not keep_internal:
        merged = merged.drop(columns=["_OUT_IDX", "_RID", "_NUMS"], errors="ignore")

    return merged.reset_index(drop=True), remaining.reset_index(drop=True)

# ==========================================
#  PART 4E: CARE-SPECIFIC NUMERIC FALLBACK (AFTER OUT FILTER)
# ==========================================

def step4_care_numeric_fallback(unmatched_step3: pd.DataFrame,
                               outstanding_path: Path,
                               deduplicate: bool = True,
                               keep_internal: bool = False):

    if unmatched_step3.empty:
        return pd.DataFrame(), unmatched_step3

    out = _get_outstanding_clean(outstanding_path)

    if "Claim No" in out.columns:
        out = out.rename(columns={"Claim No": "Claim No_out"})

    _NULL_L = {'nan', 'none', 'null', 'na', 'n/a', ''}

    _PAREN_RE2 = re.compile(r"\([^)]*\)")
    _DOT_RE2 = re.compile(r"\..*$")
    _SUFFIX_RE2 = re.compile(r"([_-])(\d{1,2})$")

    def _strip_trailing_suffix2(s: str) -> str:
        m = _SUFFIX_RE2.search(s)
        if not m:
            return s
        n = int(m.group(2))
        if 0 <= n <= 20:
            return s[:m.start()]
        return s

    def _care_clean_base(val: str) -> str:
        s = str(val).replace("\xa0", " ").strip().upper()
        if s.lower() in _NULL_L:
            return ""
        if s.endswith(".0"):
            s = s[:-2]

        s = _PAREN_RE2.sub("", s)
        s = _DOT_RE2.sub("", s)
        s = _strip_trailing_suffix2(s)

        s = re.sub(r"^\s*CLAIM\s*NO[\s\-:]*", "", s)
        s = re.sub(r"^\s*CLAIM\s*NO\.\s*", "", s)
        s = re.sub(r"^\s*AL[\s\.]*", "", s)

        if re.search(r"\d", s):
            s = re.sub(r"^\s*[A-Z]+\s*", "", s)

        return s.strip()

    def _care_numeric_tokens(val) -> list:
        if pd.isna(val):
            return []
        s = _care_clean_base(val)
        if not s:
            return []

        parts = [p.strip() for p in re.split(r"[/,&]", s) if p.strip()]
        toks = []
        for p in parts:
            p = _strip_trailing_suffix2(p)
            nums = re.findall(r"\d{6,}", p)
            for n in nums:
                toks.append(n)
        return toks

    L = out.copy().reset_index(drop=False).rename(columns={"index": "_OUT_IDX"}).copy()
    R = unmatched_step3.copy().reset_index(drop=True).copy()

    if "_STEP3_ROW_ID" not in R.columns:
        R["_STEP3_ROW_ID"] = np.arange(len(R))

    R["_RID"] = np.arange(len(R))
    R["_CARE_TOKS"] = R["Claim No"].apply(_care_numeric_tokens)

    R_exp = R[["_RID", "_CARE_TOKS"]].explode("_CARE_TOKS").dropna()
    R_exp["_CARE_TOKS"] = R_exp["_CARE_TOKS"].astype(str).str.strip()
    R_exp = R_exp[R_exp["_CARE_TOKS"] != ""].drop_duplicates()

    if R_exp.empty:
        R = R.drop(columns=["_RID", "_CARE_TOKS"], errors="ignore")
        return pd.DataFrame(), R.drop(columns=["_RID", "_CARE_TOKS"], errors="ignore")

    tok_to_rids = R_exp.groupby("_CARE_TOKS")["_RID"].apply(lambda x: set(x.tolist())).to_dict()

    picks = []
    for _, row in L.iterrows():
        toks = _care_numeric_tokens(row.get("Claim No_out", ""))
        if not toks:
            continue

        cand = set()
        ambiguous = False
        for t in toks:
            rids = tok_to_rids.get(str(t).strip())
            if not rids:
                continue
            cand |= rids
            if len(rids) > 1:
                ambiguous = True

        if ambiguous:
            continue
        if len(cand) == 1:
            picks.append({"_OUT_IDX": row["_OUT_IDX"], "_RID": list(cand)[0]})

    if not picks:
        R = R.drop(columns=["_RID", "_CARE_TOKS"], errors="ignore")
        return pd.DataFrame(), R.drop(columns=["_RID", "_CARE_TOKS"], errors="ignore")

    P = pd.DataFrame(picks).drop_duplicates(subset=["_OUT_IDX"])

    grp = P.groupby("_OUT_IDX")["_RID"].nunique().reset_index(name="_N")
    ok_out = set(grp.loc[grp["_N"] == 1, "_OUT_IDX"].tolist())
    P = P[P["_OUT_IDX"].isin(ok_out)].copy()

    L_pick = L.merge(P, on="_OUT_IDX", how="inner")
    merged = L_pick.merge(
        R,
        on="_RID",
        how="inner",
        suffixes=("_out", "_m3")
    )
    merged["MATCH_MODE"] = "CARE_NUMERIC"

    if deduplicate and not merged.empty:
        merged = merged.drop_duplicates()

    matched_rids = set(merged["_RID"].unique().tolist()) if (not merged.empty and "_RID" in merged.columns) else set()
    remaining = R[~R["_RID"].isin(matched_rids)].copy()

    remaining = remaining.drop(columns=["_RID", "_CARE_TOKS"], errors="ignore")
    if not keep_internal:
        merged = merged.drop(columns=["_OUT_IDX", "_RID", "_CARE_TOKS"], errors="ignore")

    return merged.reset_index(drop=True), remaining.reset_index(drop=True)

# ==========================================
#  PART 4F: FHPL-SPECIFIC NUMERIC FALLBACK (UNCHANGED)
# ==========================================

def step4_fhpl_numeric_fallback(unmatched_step3: pd.DataFrame,
                                outstanding_path: Path,
                                deduplicate: bool = True,
                                keep_internal: bool = False):

    if unmatched_step3.empty:
        return pd.DataFrame(), unmatched_step3

    out = _get_outstanding_clean(outstanding_path)
    if "Claim No" in out.columns:
        out = out.rename(columns={"Claim No": "Claim No_out"})

    _NULL_L = {'nan', 'none', 'null', 'na', 'n/a', ''}

    def _mis_num(val) -> str:
        if pd.isna(val):
            return ""
        s = str(val).replace("\xa0", " ").strip()
        if s.lower() in _NULL_L:
            return ""
        if "/" in s:
            s = s.split("/")[0].strip()
        s = re.sub(r"[^0-9]", "", s)
        return s.strip()

    def _out_nums(val) -> list:
        if pd.isna(val):
            return []
        s = str(val).replace("\xa0", " ").strip()
        if s.strip().lower() in _NULL_L:
            return []
        parts = [p.strip() for p in re.split(r"[/,&]", s) if p.strip()]
        toks = []
        for p in parts:
            nums = re.findall(r"\d{6,}", p)
            toks.extend(nums)
        return toks

    L = out.copy().reset_index(drop=False).rename(columns={"index": "_OUT_IDX"})
    R = unmatched_step3.copy().reset_index(drop=True)

    if "_STEP3_ROW_ID" not in R.columns:
        R["_STEP3_ROW_ID"] = np.arange(len(R))

    R["_RID"] = np.arange(len(R))
    R["_MIS_NUM"] = R["Claim No"].apply(_mis_num)
    R = R[R["_MIS_NUM"] != ""].copy()
    if R.empty:
        return pd.DataFrame(), unmatched_step3

    num_to_rids = R.groupby("_MIS_NUM")["_RID"].apply(lambda x: set(x.tolist())).to_dict()

    picks = []
    for _, row in L.iterrows():
        toks = _out_nums(row.get("Claim No_out", ""))
        if not toks:
            continue

        cand = set()
        ambiguous = False
        for t in toks:
            rids = num_to_rids.get(str(t).strip())
            if not rids:
                continue
            cand |= rids
            if len(rids) > 1:
                ambiguous = True

        if ambiguous:
            continue
        if len(cand) == 1:
            picks.append({"_OUT_IDX": row["_OUT_IDX"], "_RID": list(cand)[0]})

    if not picks:
        R = R.drop(columns=["_RID", "_MIS_NUM"], errors="ignore")
        return pd.DataFrame(), unmatched_step3

    P = pd.DataFrame(picks).drop_duplicates(subset=["_OUT_IDX"])
    grp = P.groupby("_OUT_IDX")["_RID"].nunique().reset_index(name="_N")
    ok_out = set(grp.loc[grp["_N"] == 1, "_OUT_IDX"].tolist())
    P = P[P["_OUT_IDX"].isin(ok_out)].copy()

    L_pick = L.merge(P, on="_OUT_IDX", how="inner")
    merged = L_pick.merge(R, on="_RID", how="inner", suffixes=("_out", "_m3"))
    merged["MATCH_MODE"] = "FHPL_NUMERIC"

    if deduplicate and not merged.empty:
        merged = merged.drop_duplicates()

    matched_rids = set(merged["_RID"].unique().tolist()) if (not merged.empty and "_RID" in merged.columns) else set()
    remaining = R[~R["_RID"].isin(matched_rids)].copy()

    remaining = remaining.drop(columns=["_RID", "_MIS_NUM"], errors="ignore")
    if not keep_internal:
        merged = merged.drop(columns=["_OUT_IDX", "_RID", "_MIS_NUM"], errors="ignore")

    return merged.reset_index(drop=True), remaining.reset_index(drop=True)

# ==========================================
#  PART 4G: ICICI LOMBARD OUTSTANDING SPLIT FALLBACK (UNCHANGED)
# ==========================================

def step4_icici_lombard_split_fallback(unmatched_step3: pd.DataFrame,
                                       outstanding_path: Path,
                                       deduplicate: bool = True,
                                       keep_internal: bool = False):

    if unmatched_step3.empty:
        return pd.DataFrame(), unmatched_step3

    out = _get_outstanding_clean(outstanding_path)
    if "Claim No" in out.columns:
        out = out.rename(columns={"Claim No": "Claim No_out"})

    L = out.copy().reset_index(drop=False).rename(columns={"index": "_OUT_IDX"}).copy()
    R = unmatched_step3.copy().reset_index(drop=True).copy()

    if "_STEP3_ROW_ID" not in R.columns:
        R["_STEP3_ROW_ID"] = np.arange(len(R))

    R["_RID"] = np.arange(len(R))
    R["_ALPHA_KEY"] = R["Claim No"].apply(_alpha_key)
    R = R[R["_ALPHA_KEY"] != ""].copy()
    if R.empty:
        return pd.DataFrame(), unmatched_step3

    key_to_rids = R.groupby("_ALPHA_KEY")["_RID"].apply(lambda x: set(x.tolist())).to_dict()

    def _out_split_alpha_tokens(val) -> list:
        parts = _split_tokens_any(val)
        return _alpha_tokens_from_parts(parts)

    picks = []
    for _, row in L.iterrows():
        toks = _out_split_alpha_tokens(row.get("Claim No_out", ""))
        if not toks:
            continue

        cand = set()
        ambiguous = False
        for t in toks:
            rids = key_to_rids.get(str(t).strip())
            if not rids:
                continue
            cand |= rids
            if len(rids) > 1:
                ambiguous = True

        if ambiguous:
            continue
        if len(cand) == 1:
            picks.append({"_OUT_IDX": row["_OUT_IDX"], "_RID": list(cand)[0]})

    if not picks:
        R = R.drop(columns=["_RID", "_ALPHA_KEY"], errors="ignore")
        return pd.DataFrame(), unmatched_step3

    P = pd.DataFrame(picks).drop_duplicates(subset=["_OUT_IDX"])
    grp = P.groupby("_OUT_IDX")["_RID"].nunique().reset_index(name="_N")
    ok_out = set(grp.loc[grp["_N"] == 1, "_OUT_IDX"].tolist())
    P = P[P["_OUT_IDX"].isin(ok_out)].copy()

    L_pick = L.merge(P, on="_OUT_IDX", how="inner")
    merged = L_pick.merge(R, on="_RID", how="inner", suffixes=("_out", "_m3"))
    merged["MATCH_MODE"] = "ICICI_LOMBARD_SPLIT"

    if deduplicate and not merged.empty:
        merged = merged.drop_duplicates()

    matched_rids = set(merged["_RID"].unique().tolist()) if (not merged.empty and "_RID" in merged.columns) else set()
    remaining = R[~R["_RID"].isin(matched_rids)].copy()

    remaining = remaining.drop(columns=["_RID", "_ALPHA_KEY"], errors="ignore")
    if not keep_internal:
        merged = merged.drop(columns=["_OUT_IDX", "_RID", "_ALPHA_KEY"], errors="ignore")

    return merged.reset_index(drop=True), remaining.reset_index(drop=True)

# ==========================================
#  OUTSTANDING FILTER REGISTRY (ALL 17 NON-IHX)
# ==========================================

_OUT_FILTER_RULES: Dict[str, List[str]] = {
    "PARK MEDICLAIM INSURANCE TPA PRIVATE LIMITED": ["PARK"],
    "CARE HEALTH INSURANCE LIMITED": ["CARE"],
    "HEALTH INDIA INSURANCE TPA SERVICES PRIVATE LTD.": ["HEALTH INDIA", "HEALTH"],
    "FHPL": ["FAMILY"],
    "ICICI LOMBARD": ["ICICI", "LOMBARD"],
    "FUTURE GENERALI": ["FUTURE", "GENERALI"],
    "RELIANCE": ["RELIANCE"],
    "ERICSON": ["ERICSON", "ERIC"],
    "ADITYA BIRLA": ["ADITYA", "BIRLA"],
    "SAFEWAY INSURANCE TPA PVT.LTD": ["SAFEWAY"],
    "STAR HEALTH & ALLIED HEALTH INSURANCE CO.LTD.": ["STAR"],
    "VIDAL": ["VIDAL"],
    "HERITAGE HEALTH INSURANCE TPA PRIVATE LIMITED": ["HERITAGE"],
    "MEDSAVE HEALTHCARE TPA PVT LTD": ["MEDSAVE", "MED SAVE"],
    "GOOD HEALTH": ["GOOD HEALTH", "GOODHEALTH", "GOOD"],
    "VOLO HEALTH INSURANCE TPA PVT.LTD (EWA) (Mail Extract)": ["VOLO"],
    "SBI GENERAL": ["SBI"],
}

def filter_outstanding_for_tpa(out_clean: pd.DataFrame, tpa_choice: str) -> pd.DataFrame:
    if "Bill Company Name" not in out_clean.columns:
        raise ValueError("Outstanding cleaned is missing 'Bill Company Name' - cannot filter by TPA.")

    if tpa_choice == "IHX (Original MIS)":
        return out_clean.copy()

    if tpa_choice not in _OUT_FILTER_RULES:
        raise ValueError(
            f"Non-IHX TPA detected ('{tpa_choice}') but no TPA-wise outstanding filter rule is defined yet. "
            f"Add it to _OUT_FILTER_RULES before running."
        )

    tokens = [t.upper() for t in _OUT_FILTER_RULES[tpa_choice] if str(t).strip()]
    bn = out_clean["Bill Company Name"].astype(str).str.upper()

    mask = False
    for tok in tokens:
        mask = mask | bn.str.contains(tok, na=False)

    out_filt = out_clean.loc[mask].copy()

    if out_filt.empty:
        raise ValueError(
            f"TPA-wise outstanding filter produced 0 rows for TPA '{tpa_choice}'. "
            f"This is fail-fast to prevent cross-TPA matching chaos. "
            f"Check Bill Company Name values and update _OUT_FILTER_RULES tokens."
        )
    return out_filt.reset_index(drop=True)

# ==========================================
#  NON-IHX MATCH PLAN REGISTRY (TPA-GATED)
# ==========================================

def run_step4_plan(step3_df: pd.DataFrame, out_input, tpa_choice: str, keep_internal: bool = False) -> Tuple[pd.DataFrame, pd.DataFrame]:
    if tpa_choice == "IHX (Original MIS)":
        return step4_strict_matches(step3_df, out_input, deduplicate=True, keep_internal=keep_internal)

    if tpa_choice in [
        "PARK MEDICLAIM INSURANCE TPA PRIVATE LIMITED",
        "HEALTH INDIA INSURANCE TPA SERVICES PRIVATE LTD.",
        "FUTURE GENERALI",
        "RELIANCE",
        "ERICSON",
        "ADITYA BIRLA",
        "SAFEWAY INSURANCE TPA PVT.LTD",
        "STAR HEALTH & ALLIED HEALTH INSURANCE CO.LTD.",
        "HERITAGE HEALTH INSURANCE TPA PRIVATE LIMITED",
        "MEDSAVE HEALTHCARE TPA PVT LTD",
    ]:
        return step4_alpha_strict_unique(step3_df, out_input, deduplicate=True, match_mode="ALPHA_STRICT_UNIQUE", keep_internal=keep_internal)

    if tpa_choice == "VIDAL":
        m1, rem = step4_split_alpha_unique(step3_df, out_input, deduplicate=True, match_mode="VIDAL_SPLIT_ALPHA_UNIQUE", keep_internal=keep_internal)
        if m1.empty:
            return step4_alpha_strict_unique(step3_df, out_input, deduplicate=True, match_mode="VIDAL_ALPHA_UNIQUE", keep_internal=keep_internal)
        return m1, rem

    if tpa_choice in [
        "GOOD HEALTH",
        "VOLO HEALTH INSURANCE TPA PVT.LTD (EWA) (Mail Extract)",
        "SBI GENERAL",
    ]:
        return step4_numeric_split_unique(step3_df, out_input, deduplicate=True, match_mode="NUMERIC_SPLIT_UNIQUE", min_len=6, keep_internal=keep_internal)

    if tpa_choice == "CARE HEALTH INSURANCE LIMITED":
        m1, rem = step4_alpha_strict_unique(step3_df, out_input, deduplicate=True, match_mode="ALPHA_STRICT_UNIQUE", keep_internal=keep_internal)
        m2, rem2 = step4_care_numeric_fallback(rem, out_input, deduplicate=True, keep_internal=keep_internal)
        if not m2.empty:
            m1 = pd.concat([m1, m2], ignore_index=True)
        return m1, rem2

    if tpa_choice == "FHPL":
        m1, rem = step4_alpha_strict_unique(step3_df, out_input, deduplicate=True, match_mode="ALPHA_STRICT_UNIQUE", keep_internal=keep_internal)
        m2, rem2 = step4_fhpl_numeric_fallback(rem, out_input, deduplicate=True, keep_internal=keep_internal)
        if not m2.empty:
            m1 = pd.concat([m1, m2], ignore_index=True)
        return m1, rem2

    if tpa_choice == "ICICI LOMBARD":
        m1, rem = step4_alpha_strict_unique(step3_df, out_input, deduplicate=True, match_mode="ALPHA_STRICT_UNIQUE", keep_internal=keep_internal)
        m2, rem2 = step4_icici_lombard_split_fallback(rem, out_input, deduplicate=True, keep_internal=keep_internal)
        if not m2.empty:
            m1 = pd.concat([m1, m2], ignore_index=True)
        return m1, rem2

    raise ValueError(
        f"Non-IHX TPA detected ('{tpa_choice}') but no Step-4 match plan is defined in run_step4_plan()."
    )

# ==========================================
#  CLASSIFICATION / METRICS / DOCUMENTATION
# ==========================================

def classify_step3_matches(step3_candidate_df: pd.DataFrame,
                           bank_type: str,
                           tpa_choice: str,
                           run_id: str) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, Dict[str, int]]:

    if step3_candidate_df.empty:
        metrics = {
            "step3_candidate_pairs": 0,
            "step3_auto_rows": 0,
            "step3_review_rows": 0,
        }
        return pd.DataFrame(), pd.DataFrame(), pd.DataFrame(), metrics

    df = step3_candidate_df.copy().reset_index(drop=True)
    if "_STEP3_ROW_ID" not in df.columns:
        df["_STEP3_ROW_ID"] = np.arange(len(df))

    _ensure_required_columns(
        df,
        ["_BANK_ROW_ID", "_MIS_ROW_ID", "UTR_RAW", "CLAIM_RAW", "UTR_KEY", "CLAIM_KEY", "PAIR_KEY_RAW", "PAIR_KEY"],
        "Step3 classification"
    )

    bank_counts = df.groupby("_BANK_ROW_ID")["_MIS_ROW_ID"].nunique().to_dict()
    mis_counts = df.groupby("_MIS_ROW_ID")["_BANK_ROW_ID"].nunique().to_dict()
    pair_counts = df["PAIR_KEY"].fillna("").astype(str).value_counts().to_dict()

    df["LEFT_MATCH_COUNT"] = df["_BANK_ROW_ID"].map(bank_counts).fillna(0).astype(int)
    df["RIGHT_MATCH_COUNT"] = df["_MIS_ROW_ID"].map(mis_counts).fillna(0).astype(int)
    df["MATCH_CARDINALITY"] = df.apply(
        lambda r: _cardinality_label(int(r["LEFT_MATCH_COUNT"]), int(r["RIGHT_MATCH_COUNT"])),
        axis=1
    )
    df["PAIR_STATUS"] = df["PAIR_KEY"].fillna("").astype(str).map(
        lambda x: _pair_status_from_counts(pair_counts.get(x, 0))
    )

    df["AUTO_REVIEW_STATUS"] = np.where(df["MATCH_CARDINALITY"] == "ONE_TO_ONE", "AUTO", "REVIEW")
    df["REVIEW_STAGE"] = "STEP3"
    df["REVIEW_REASON"] = df.apply(
        lambda r: _build_review_reason(r["PAIR_STATUS"], r["MATCH_CARDINALITY"]),
        axis=1
    )
    df["BANK_TYPE"] = bank_type
    df["TPA_CHOICE"] = tpa_choice
    df["RUN_ID"] = run_id
    df["MATCH_MODE"] = "UTR_EXACT_FULL"

    auto_df = df[df["AUTO_REVIEW_STATUS"] == "AUTO"].copy()
    review_df = df[df["AUTO_REVIEW_STATUS"] == "REVIEW"].copy()
    full_df = df.copy()

    metrics = {
        "step3_candidate_pairs": int(len(full_df)),
        "step3_auto_rows": int(len(auto_df)),
        "step3_review_rows": int(len(review_df)),
    }

    return _sanitize_for_output(auto_df), _sanitize_for_output(review_df), _sanitize_for_output(full_df), metrics

def classify_step4_matches(step4_candidate_df: pd.DataFrame,
                           bank_type: str,
                           tpa_choice: str,
                           run_id: str) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, Dict[str, int]]:

    if step4_candidate_df.empty:
        metrics = {
            "step4_candidate_pairs": 0,
            "step4_auto_rows": 0,
            "step4_review_rows": 0,
        }
        return pd.DataFrame(), pd.DataFrame(), pd.DataFrame(), metrics

    df = step4_candidate_df.copy().reset_index(drop=True)

    _ensure_required_columns(
        df,
        ["_OUT_IDX", "_STEP3_ROW_ID", "UTR_RAW", "CLAIM_RAW", "UTR_KEY", "CLAIM_KEY", "PAIR_KEY_RAW", "PAIR_KEY", "MATCH_MODE"],
        "Step4 classification"
    )

    out_counts = df.groupby("_OUT_IDX")["_STEP3_ROW_ID"].nunique().to_dict()
    step3_counts = df.groupby("_STEP3_ROW_ID")["_OUT_IDX"].nunique().to_dict()
    pair_counts = df["PAIR_KEY"].fillna("").astype(str).value_counts().to_dict()

    df["LEFT_MATCH_COUNT"] = df["_OUT_IDX"].map(out_counts).fillna(0).astype(int)
    df["RIGHT_MATCH_COUNT"] = df["_STEP3_ROW_ID"].map(step3_counts).fillna(0).astype(int)
    df["MATCH_CARDINALITY"] = df.apply(
        lambda r: _cardinality_label(int(r["LEFT_MATCH_COUNT"]), int(r["RIGHT_MATCH_COUNT"])),
        axis=1
    )
    df["PAIR_STATUS"] = df["PAIR_KEY"].fillna("").astype(str).map(
        lambda x: _pair_status_from_counts(pair_counts.get(x, 0))
    )

    df["AUTO_REVIEW_STATUS"] = np.where(df["MATCH_CARDINALITY"] == "ONE_TO_ONE", "AUTO", "REVIEW")
    df["REVIEW_STAGE"] = "STEP4"
    df["REVIEW_REASON"] = df.apply(
        lambda r: _build_review_reason(r["PAIR_STATUS"], r["MATCH_CARDINALITY"]),
        axis=1
    )
    df["BANK_TYPE"] = bank_type
    df["TPA_CHOICE"] = tpa_choice
    df["RUN_ID"] = run_id

    auto_df = df[df["AUTO_REVIEW_STATUS"] == "AUTO"].copy()
    review_df = df[df["AUTO_REVIEW_STATUS"] == "REVIEW"].copy()
    full_df = df.copy()

    metrics = {
        "step4_candidate_pairs": int(len(full_df)),
        "step4_auto_rows": int(len(auto_df)),
        "step4_review_rows": int(len(review_df)),
    }

    return _sanitize_for_output(auto_df), _sanitize_for_output(review_df), _sanitize_for_output(full_df), metrics

def build_metrics_df(metrics: Dict[str, object]) -> pd.DataFrame:
    rows = [{"METRIC": k, "VALUE": v} for k, v in metrics.items()]
    return pd.DataFrame(rows)

def build_documentation_workbook(path: Path):
    col_index = pd.DataFrame([
        {"COLUMN_NAME": "AUTO_REVIEW_STATUS", "CATEGORY": "Audit", "DESCRIPTION": "Whether the row is auto-safe or must be manually reviewed.", "SOURCE_STAGE": "STEP3/STEP4", "AUTO_USED": "Yes", "REVIEW_USED": "Yes"},
        {"COLUMN_NAME": "REVIEW_STAGE", "CATEGORY": "Audit", "DESCRIPTION": "The stage at which the row was classified: STEP3 or STEP4.", "SOURCE_STAGE": "STEP3/STEP4", "AUTO_USED": "Yes", "REVIEW_USED": "Yes"},
        {"COLUMN_NAME": "REVIEW_REASON", "CATEGORY": "Audit", "DESCRIPTION": "Plain-meaning structural reason for AUTO/REVIEW classification.", "SOURCE_STAGE": "STEP3/STEP4", "AUTO_USED": "Yes", "REVIEW_USED": "Yes"},
        {"COLUMN_NAME": "PAIR_STATUS", "CATEGORY": "Trace", "DESCRIPTION": "Whether the cleaned (UTR, Claim No) pair appeared once or multiple times within candidate rows at that stage.", "SOURCE_STAGE": "STEP3/STEP4", "AUTO_USED": "Yes", "REVIEW_USED": "Yes"},
        {"COLUMN_NAME": "MATCH_CARDINALITY", "CATEGORY": "Structure", "DESCRIPTION": "Realized match shape: ONE_TO_ONE, ONE_TO_MANY, MANY_TO_ONE, MANY_TO_MANY.", "SOURCE_STAGE": "STEP3/STEP4", "AUTO_USED": "Yes", "REVIEW_USED": "Yes"},
        {"COLUMN_NAME": "LEFT_MATCH_COUNT", "CATEGORY": "Structure", "DESCRIPTION": "Number of matches seen from the left-side entity at the classification stage.", "SOURCE_STAGE": "STEP3/STEP4", "AUTO_USED": "Yes", "REVIEW_USED": "Yes"},
        {"COLUMN_NAME": "RIGHT_MATCH_COUNT", "CATEGORY": "Structure", "DESCRIPTION": "Number of matches seen from the right-side entity at the classification stage.", "SOURCE_STAGE": "STEP3/STEP4", "AUTO_USED": "Yes", "REVIEW_USED": "Yes"},
        {"COLUMN_NAME": "BANK_TYPE", "CATEGORY": "Run Context", "DESCRIPTION": "Auto-detected bank type used for the run.", "SOURCE_STAGE": "Run", "AUTO_USED": "Yes", "REVIEW_USED": "Yes"},
        {"COLUMN_NAME": "TPA_CHOICE", "CATEGORY": "Run Context", "DESCRIPTION": "Auto-detected TPA choice used for the run.", "SOURCE_STAGE": "Run", "AUTO_USED": "Yes", "REVIEW_USED": "Yes"},
        {"COLUMN_NAME": "MATCH_MODE", "CATEGORY": "Run Context", "DESCRIPTION": "Specific match rule that produced the row.", "SOURCE_STAGE": "STEP3/STEP4", "AUTO_USED": "Yes", "REVIEW_USED": "Yes"},
        {"COLUMN_NAME": "RUN_ID", "CATEGORY": "Run Context", "DESCRIPTION": "Unique identifier for the bank+MIS run.", "SOURCE_STAGE": "Run", "AUTO_USED": "Yes", "REVIEW_USED": "Yes"},
        {"COLUMN_NAME": "UTR_RAW", "CATEGORY": "Trace", "DESCRIPTION": "Raw UTR value before cleaned-key normalization.", "SOURCE_STAGE": "STEP3", "AUTO_USED": "Yes", "REVIEW_USED": "Yes"},
        {"COLUMN_NAME": "CLAIM_RAW", "CATEGORY": "Trace", "DESCRIPTION": "Raw claim value before cleaned-key normalization.", "SOURCE_STAGE": "STEP3", "AUTO_USED": "Yes", "REVIEW_USED": "Yes"},
        {"COLUMN_NAME": "PAIR_KEY_RAW", "CATEGORY": "Trace", "DESCRIPTION": "Raw pair key built as raw UTR + raw Claim No.", "SOURCE_STAGE": "STEP3", "AUTO_USED": "Yes", "REVIEW_USED": "Yes"},
        {"COLUMN_NAME": "UTR_KEY", "CATEGORY": "Trace", "DESCRIPTION": "Cleaned full UTR key used for exact substring bank↔MIS matching.", "SOURCE_STAGE": "STEP3", "AUTO_USED": "Yes", "REVIEW_USED": "Yes"},
        {"COLUMN_NAME": "CLAIM_KEY", "CATEGORY": "Trace", "DESCRIPTION": "Cleaned claim key used for traceability of the pair key.", "SOURCE_STAGE": "STEP3", "AUTO_USED": "Yes", "REVIEW_USED": "Yes"},
        {"COLUMN_NAME": "PAIR_KEY", "CATEGORY": "Trace", "DESCRIPTION": "Cleaned pair key built as cleaned UTR + cleaned Claim No.", "SOURCE_STAGE": "STEP3", "AUTO_USED": "Yes", "REVIEW_USED": "Yes"},
    ])

    reason_defs = pd.DataFrame([
        {"VALUE": "PAIR_UNIQUE | ONE_TO_ONE", "MEANING": "Unique pair and structurally one-to-one."},
        {"VALUE": "PAIR_UNIQUE | ONE_TO_MANY", "MEANING": "Unique pair but one left-side record linked to multiple right-side records."},
        {"VALUE": "PAIR_UNIQUE | MANY_TO_ONE", "MEANING": "Unique pair but multiple left-side records linked to one right-side record."},
        {"VALUE": "PAIR_UNIQUE | MANY_TO_MANY", "MEANING": "Unique pair but multiple records existed on both sides."},
        {"VALUE": "PAIR_DUPLICATE | ONE_TO_ONE", "MEANING": "Duplicate pair but realized one-to-one row linkage at that stage."},
        {"VALUE": "PAIR_DUPLICATE | ONE_TO_MANY", "MEANING": "Duplicate pair with one-to-many realized shape."},
        {"VALUE": "PAIR_DUPLICATE | MANY_TO_ONE", "MEANING": "Duplicate pair with many-to-one realized shape."},
        {"VALUE": "PAIR_DUPLICATE | MANY_TO_MANY", "MEANING": "Duplicate pair with many-to-many realized shape."},
    ])

    card_defs = pd.DataFrame([
        {"VALUE": "ONE_TO_ONE", "MEANING": "Exactly one matching row on both sides."},
        {"VALUE": "ONE_TO_MANY", "MEANING": "One left-side row linked to multiple right-side rows."},
        {"VALUE": "MANY_TO_ONE", "MEANING": "Multiple left-side rows linked to one right-side row."},
        {"VALUE": "MANY_TO_MANY", "MEANING": "Multiple rows existed on both sides of the linkage."},
    ])

    run_meta = pd.DataFrame([
        {"FIELD": "07_final_posting_sheet.xlsx", "MEANING": "AUTO-safe final posting rows only."},
        {"FIELD": "07_review_queue.xlsx", "MEANING": "Combined review queue containing all rows flagged for manual review."},
        {"FIELD": "05_step3_review.xlsx", "MEANING": "Rows flagged for review at Bank↔MIS matching stage."},
        {"FIELD": "06_step4_review.xlsx", "MEANING": "Rows flagged for review at Outstanding matching stage."},
        {"FIELD": "07_run_metrics.xlsx", "MEANING": "Run counts and stage-level reconciliation metrics."},
    ])

    with pd.ExcelWriter(path, engine="openpyxl") as writer:
        col_index.to_excel(writer, sheet_name="Column_Index", index=False)
        reason_defs.to_excel(writer, sheet_name="Review_Reason_Definitions", index=False)
        card_defs.to_excel(writer, sheet_name="Cardinality_Definitions", index=False)
        run_meta.to_excel(writer, sheet_name="Run_Metadata_Explanation", index=False)

# ==========================================
#  PART 5: RUNNERS
# ==========================================

def _assert_exists(p: Path, label: str):
    if not p.exists():
        raise FileNotFoundError(f"{label} not found in runtime: {p}")

def _run_recon_core(bank_path: Path, mis_path: Path, out_path: Path, run_dir: Path = None) -> Dict[str, object]:
    run_id = f"{bank_path.stem}__{mis_path.stem}"

    bank_path = normalize_to_xlsx(bank_path)
    mis_path  = normalize_to_xlsx(mis_path)
    out_path  = normalize_to_xlsx(out_path)

    BANK_TYPE = detect_bank_type(bank_path)
    TPA_CHOICE = detect_tpa_choice(mis_path)

    if BANK_TYPE == "ICICI":
        bank_df = clean_raw_bank_statement_icici(bank_path)
    else:
        bank_df = clean_raw_bank_statement_axis(bank_path)

    mis_clean = parse_mis_universal(mis_path, tpa_name=TPA_CHOICE, empty_threshold=0.5)
    step3_candidate_df, step3_unmatched_bank = step2_match_bank_mis_by_utr(
        bank_df, mis_clean, TPA_CHOICE, deduplicate=True, min_key_len=8
    )

    out_clean = parse_outstanding_excel_to_clean(out_path)

    step3_auto, step3_review, step3_full, step3_metrics = classify_step3_matches(
        step3_candidate_df, BANK_TYPE, TPA_CHOICE, run_id
    )

    if TPA_CHOICE == "IHX (Original MIS)":
        step4_candidate_df, unmatched_after_step4 = step4_strict_matches(
            step3_auto, out_path, deduplicate=True, keep_internal=True
        )
        out_filt = out_clean.copy()
    else:
        out_filt = filter_outstanding_for_tpa(out_clean, TPA_CHOICE)
        out_for_step4_path = run_dir / "06_outstanding_filtered.xlsx" if run_dir is not None else Path("06_outstanding_filtered.xlsx")
        out_filt.to_excel(out_for_step4_path, index=False)

        step4_candidate_df, unmatched_after_step4 = run_step4_plan(
            step3_auto, out_for_step4_path, TPA_CHOICE, keep_internal=True
        )

    step4_auto, step4_review, step4_full, step4_metrics = classify_step4_matches(
        step4_candidate_df, BANK_TYPE, TPA_CHOICE, run_id
    )

    final_review = (
        pd.concat([step3_review, step4_review], ignore_index=True)
        if (not step3_review.empty or not step4_review.empty)
        else pd.DataFrame()
    )

    metrics = {
        "RUN_ID": run_id,
        "BANK_TYPE": BANK_TYPE,
        "TPA_CHOICE": TPA_CHOICE,
        "bank_rows_clean": len(bank_df),
        "mis_rows_clean": len(mis_clean),
        "outstanding_rows_clean": len(out_clean),
        "outstanding_rows_filtered": len(out_filt),
        "step3_candidate_pairs": step3_metrics["step3_candidate_pairs"],
        "step3_auto_rows": step3_metrics["step3_auto_rows"],
        "step3_review_rows": step3_metrics["step3_review_rows"],
        "step3_unmatched_bank_rows": len(step3_unmatched_bank),
        "step4_candidate_pairs": step4_metrics["step4_candidate_pairs"],
        "step4_auto_rows": step4_metrics["step4_auto_rows"],
        "step4_review_rows": step4_metrics["step4_review_rows"],
        "step4_unmatched_rows": len(unmatched_after_step4),
        "final_auto_rows": len(step4_auto),
        "final_review_rows": len(final_review),
    }

    outputs = {
        "BANK_TYPE": BANK_TYPE,
        "TPA_CHOICE": TPA_CHOICE,
        "bank_df": bank_df,
        "mis_clean": mis_clean,
        "step3_full": step3_full,
        "step3_auto": step3_auto,
        "step3_review": step3_review,
        "step3_unmatched_bank": step3_unmatched_bank,
        "out_clean": out_clean,
        "out_filt": out_filt,
        "step4_full": step4_full,
        "step4_auto": step4_auto,
        "step4_review": step4_review,
        "final_review": final_review,
        "metrics": metrics,
    }
    return outputs

def _save_run_outputs(outputs: Dict[str, object], run_dir: Path):
    run_dir.mkdir(exist_ok=True, parents=True)

    outputs["bank_df"].to_excel(run_dir / "01_bank_clean.xlsx", index=False)
    outputs["mis_clean"].to_excel(run_dir / "04_mis_cleaned.xlsx", index=False)
    outputs["step3_full"].to_excel(run_dir / "05_bank_mis_mapped.xlsx", index=False)
    outputs["step3_review"].to_excel(run_dir / "05_step3_review.xlsx", index=False)
    outputs["out_clean"].to_excel(run_dir / "06_outstanding_cleaned.xlsx", index=False)

    if outputs["TPA_CHOICE"] != "IHX (Original MIS)":
        outputs["out_filt"].to_excel(run_dir / "06_outstanding_filtered.xlsx", index=False)

    outputs["step4_review"].to_excel(run_dir / "06_step4_review.xlsx", index=False)
    outputs["step4_auto"].to_excel(run_dir / "07_final_posting_sheet.xlsx", index=False)
    outputs["final_review"].to_excel(run_dir / "07_review_queue.xlsx", index=False)
    build_metrics_df(outputs["metrics"]).to_excel(run_dir / "07_run_metrics.xlsx", index=False)
    build_documentation_workbook(run_dir / "00_run_documentation.xlsx")

def run_single_lane():
    print("\nEnter Filenames (files must already be uploaded in Colab runtime sidebar):")
    bank_file = input("Bank File (e.g. bank.xlsx): ").strip()
    mis_file  = input("MIS File  (e.g. mis.xlsm): ").strip()
    out_file  = input("Outstanding File (e.g. outstanding.xlsx): ").strip()

    if not bank_file or not mis_file or not out_file:
        raise ValueError("Bank/MIS/Outstanding filenames are required.")

    bank_path = Path(bank_file)
    mis_path  = Path(mis_file)
    out_path  = Path(out_file)

    _assert_exists(bank_path, "Bank file")
    _assert_exists(mis_path, "MIS file")
    _assert_exists(out_path, "Outstanding file")

    outputs = _run_recon_core(bank_path, mis_path, out_path, run_dir=Path("."))

    _save_run_outputs(outputs, Path("."))

    print(f"\nBank: {outputs['BANK_TYPE']} | TPA: {outputs['TPA_CHOICE']}")
    for k, v in outputs["metrics"].items():
        if k in ("RUN_ID", "BANK_TYPE", "TPA_CHOICE"):
            continue
        print(f"{k}: {v}")

def run_bulk_mode():
    print("\nBULK MODE — files already uploaded in Colab runtime sidebar")
    bank_input = input("Enter BANK filenames (comma separated): ").strip()
    mis_input  = input("Enter MIS filenames (comma separated): ").strip()
    out_file   = input("Outstanding filename (single file): ").strip()

    if not bank_input or not mis_input or not out_file:
        raise ValueError("Bank files, MIS files, and Outstanding file are all required.")

    bank_files = [Path(x.strip()) for x in bank_input.split(",") if x.strip()]
    mis_files  = [Path(x.strip()) for x in mis_input.split(",") if x.strip()]
    out_path   = Path(out_file.strip())

    for p in bank_files:
        _assert_exists(p, "Bank file")
    for p in mis_files:
        _assert_exists(p, "MIS file")
    _assert_exists(out_path, "Outstanding file")

    output_root = Path("bulk_outputs")
    output_root.mkdir(exist_ok=True)

    summary_rows = []

    print(f"\nFound {len(bank_files)} bank file(s) and {len(mis_files)} MIS file(s).")
    print(f"Outstanding: {out_path.resolve()}")
    print(f"Output root: {output_root.resolve()}")

    for bank_path in bank_files:
        for mis_path in mis_files:
            run_id = f"{bank_path.stem}__{mis_path.stem}"
            print(f"\n--- RUN: {run_id} ---")

            try:
                temp_run_dir = output_root / "temp"
                temp_run_dir.mkdir(parents=True, exist_ok=True)
                outputs = _run_recon_core(bank_path, mis_path, out_path, run_dir=temp_run_dir)

                run_dir = output_root / f"{bank_path.stem}__{outputs['TPA_CHOICE']}__{outputs['BANK_TYPE']}"
                _save_run_outputs(outputs, run_dir)

                print(
                    f"OK | Final AUTO rows: {len(outputs['step4_auto'])} "
                    f"| Review rows: {len(outputs['final_review'])} "
                    f"| Folder: {run_dir}"
                )

                row = {
                    "bank_file": bank_path.name,
                    "mis_file": mis_path.name,
                    "bank_type": outputs["BANK_TYPE"],
                    "tpa": outputs["TPA_CHOICE"],
                    "status": "OK",
                    "error": "",
                }
                row.update(outputs["metrics"])
                summary_rows.append(row)

            except Exception as e:
                print(f"FAILED | {run_id} | {e}")
                summary_rows.append({
                    "bank_file": bank_path.name,
                    "mis_file": mis_path.name,
                    "bank_type": "",
                    "tpa": "",
                    "status": "FAILED",
                    "error": str(e)
                })

    summary_df = pd.DataFrame(summary_rows)
    summary_df.to_excel("bulk_summary.xlsx", index=False)
    print("\nSaved bulk_summary.xlsx")
    print("Done.")

def main():
    mode = input("Run mode? 1=Interactive (default), 2=Bulk : ").strip() or "1"
    if mode == "2":
        run_bulk_mode()
    else:
        run_single_lane()

if __name__ == "__main__":
    main()